import pandas as pd
import matplotlib.pyplot as plt
import sys
 
def plot_telemetry(csv_path):
    # Load telemetry generated by main.cpp
    df = pd.read_csv(csv_path, names=['Time', 'Velocity', 'LatAccel', 'YawRate'])
    
    fig, axs = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
    fig.suptitle('ApexDynamics Vehicle Telemetry: Step-Steer Scenario')
    
    axs[0].plot(df['Time'], df['Velocity'], 'b-', label='Velocity (m/s)')
    axs[0].set_ylabel('Velocity')
    axs[0].grid(True)
    
    axs[1].plot(df['Time'], df['LatAccel'], 'r-', label='Lat Accel (m/s^2)')
    axs[1].set_ylabel('Lateral Accel')
    axs[1].grid(True)
    
    axs[2].plot(df['Time'], df['YawRate'], 'g-', label='Yaw Rate (rad/s)')
    axs[2].set_ylabel('Yaw Rate')
    axs[2].set_xlabel('Time (s)')
    axs[2].grid(True)
    
    plt.tight_layout()
    plt.savefig('telemetry_report.png', dpi=300)
    print("Saved telemetry_report.png")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python plot_telemetry.py <data.csv>")
    else:
        plot_telemetry(sys.argv[1])
